import { addDays, subDays } from 'date-fns';
import { Project, Task, Proxy, ApiKey, Subscription, Transaction } from './types';

export const SAMPLE_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Видимость таба КП готово у всех операторов',
    description: 'Оптимизация видимости вкладок для операторского состава.',
    status: 'done',
    priority: 'high',
    comments: [],
    dueDate: new Date(2026, 2, 28),
    amount: 1000,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't2',
    title: 'Полный список писем для операторов',
    description: 'Добавил полный список писем, теперь оператор может видеть весь список, даже если не успел обработать вовремя.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2025, 2, 28),
    amount: 200,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't3',
    title: 'Чат - техподдержка',
    description: 'Интеграция функционала чата техподдержки.',
    status: 'done',
    priority: 'high',
    comments: [],
    dueDate: new Date(2026, 2, 27),
    amount: 1200,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't4',
    title: 'Кнопка "Предварительно утвердить" и логика',
    description: 'Реализация кнопки и бизнес-логики предварительного утверждения.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 2, 28),
    amount: 1500,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't5',
    title: 'Маркеры менеджер',
    description: 'Добавление системы маркеров для менеджеров.',
    status: 'done',
    priority: 'low',
    comments: [],
    dueDate: new Date(2026, 2, 28),
    amount: 200,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't6',
    title: 'Сортировка по маркерам у РУ закупщика',
    description: 'Реализация сортировки для РУ закупщиков.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 2, 27),
    amount: 700,
    isPaid: false,
    isAgreed: true,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/company/personal/user/189/tasks/task/view/8835/',
  },
  {
    id: 't7',
    title: 'CN закупщик пишет всем менеджерам-адресатам',
    description: 'Массовая рассылка сообщений от CN закупщика.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 2, 29),
    amount: 600,
    isPaid: false,
    isAgreed: true,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/online/?IM_DIALOG=107&IM_MESSAGE=811603',
  },
  {
    id: 't8',
    title: 'Бронирование заказа',
    description: 'Функционал бронирования заказов в системе.',
    status: 'done',
    priority: 'high',
    comments: [],
    dueDate: new Date(2026, 2, 29),
    amount: 2000,
    isPaid: false,
    isAgreed: true,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/online/?IM_DIALOG=107&IM_MESSAGE=812363',
  },
  {
    id: 't9',
    title: 'Официалы в листинге желтыми',
    description: 'Цветовая индикация официальных лиц в общем списке.',
    status: 'done',
    priority: 'low',
    comments: [],
    dueDate: new Date(2026, 3, 1),
    amount: 200,
    isPaid: false,
    isAgreed: true,
  },
  {
    id: 't10',
    title: 'Изменения join.1688.broker step 1 и step 3',
    description: 'Доработка шагов 1 и 3 в брокере 1688.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 3, 1),
    amount: 200,
    isPaid: false,
    isAgreed: true,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/workgroups/group/21/tasks/task/view/8823/',
  },
  {
    id: 't11',
    title: 'Настройки редактирования заказа',
    description: 'Вывод настроек редактирования заказа в интерфейс.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 3, 1),
    amount: 500,
    isPaid: false,
    isAgreed: false,
  },
  {
    id: 't12',
    title: 'Кол-во позиций в листинге у закупщика CN',
    description: 'Отображение количества позиций для китайских закупщиков.',
    status: 'done',
    priority: 'medium',
    comments: [],
    dueDate: new Date(2026, 3, 2),
    amount: 200,
    isPaid: false,
    isAgreed: false,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/workgroups/group/21/tasks/task/view/8989/',
  },
  {
    id: 't13',
    title: 'Фиксация шапки и удаление футера',
    description: 'Стилевые правки в детальной карточке заказа.',
    status: 'done',
    priority: 'low',
    comments: [],
    dueDate: new Date(2026, 3, 2),
    amount: 500,
    isPaid: false,
    isAgreed: false,
    externalUrl: 'https://b24-uvqf0e.bitrix24.ru/online/?IM_DIALOG=chat7727&IM_MESSAGE=833801',
  },
  {
    id: 't14',
    title: 'Подписка на бренды',
    description: 'Реализация системы подписок на бренды.',
    status: 'todo',
    priority: 'high',
    comments: [],
    dueDate: new Date(2026, 3, 1),
    amount: 2500,
    isPaid: false,
    isAgreed: false,
  }
];

export const SAMPLE_PROXIES: Proxy[] = [
  {
    id: 'p1',
    ip: '186.179.63.76',
    port: '9707',
    login: 'xYPdCo',
    passwordHash: 'RBu7mj',
    type: 'HTTPS',
    expiresAt: addDays(new Date(), 7),
    comment: 'Для нового аккаунта',
    isShared: true,
  },
  {
    id: 'p2',
    ip: '45.145.57.235',
    port: '12422',
    login: 'WSZ3DZ',
    passwordHash: 'f88xRY',
    type: 'HTTPS',
    ipv6: '2a10:6d41:5369:0f06:5441:81bd:445a:f79e',
    expiresAt: addDays(new Date(), 16),
  }
];

export const SAMPLE_API_KEYS: ApiKey[] = [
  {
    id: 'a1',
    name: 'OpenAI Main',
    key: 'sk-proj-********************',
    usageLocation: 'Backend Server 1',
    expiresAt: addDays(new Date(), 30),
  },
  {
    id: 'a2',
    name: 'Stripe Live',
    key: 'pk_live_********************',
    usageLocation: 'Payment Gateway',
    expiresAt: addDays(new Date(), 365),
  }
];

export const SAMPLE_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 's1',
    serviceName: 'Cosmo Hosting Pro',
    expiresAt: addDays(new Date(), 14),
  },
  {
    id: 's2',
    serviceName: 'API Premium Access',
    expiresAt: addDays(new Date(), 5),
  }
];

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  { id: 'tr1', name: 'Proxy Renewal', date: subDays(new Date(), 0), amount: 45.00, type: 'expense', category: 'Infrastructure', status: 'Completed' },
  { id: 'tr2', name: 'Client Payment', date: subDays(new Date(), 1), amount: 1200.00, type: 'income', category: 'Services', status: 'Completed' },
  { id: 'tr3', name: 'API Subscription', date: subDays(new Date(), 3), amount: 29.99, type: 'expense', category: 'Software', status: 'Pending' },
  { id: 'tr4', name: 'Server Hosting', date: subDays(new Date(), 5), amount: 150.00, type: 'expense', category: 'Infrastructure', status: 'Completed' },
];

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj1',
    name: 'Cosmo Dashboard',
    description: 'Main project management tool.',
    proxies: SAMPLE_PROXIES,
    apiKeys: SAMPLE_API_KEYS,
    subscriptions: SAMPLE_SUBSCRIPTIONS,
    tasks: SAMPLE_TASKS,
    transactions: SAMPLE_TRANSACTIONS,
    createdAt: subDays(new Date(), 30),
  },
  {
    id: 'proj2',
    name: 'Nebula App',
    description: 'A mobile application for nebula tracking.',
    proxies: [],
    apiKeys: [],
    subscriptions: [],
    tasks: [],
    transactions: [],
    createdAt: subDays(new Date(), 10),
  }
];
